### ISSUE TITLE
Database Error with OC 7.0.2

### ISSUE THREAD

**Issue by tadeomarti** [arnovr/ocusagecharts#49]
I recently installed ocUsageCharts v3.2 on my ownCloud v7.0.2.1. At charts menu the stats from my users are not shown.

![captura](https://cloud.githubusercontent.com/assets/8223446/4766891/674bf186-5b57-11e4-8a6f-8931cbd1dc1c.PNG)

Log show this error:
Fatal 	index 	Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT DISTINCT CONCAT(MONTH("created"), ' ', YEAR("created")) as month, avg("usage") as average, username FROM oc_uc_storageusage WHERE "usage" > 0 AND created > ? GROUP BY username, month': SQLSTATE[42883]: Undefined function: 7 ERROR: function month(timestamp without time zone) does not exist LINE 1: SELECT DISTINCT CONCAT(MONTH("created"), ' ', YEAR("created"... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts

My ownCloud is running under:
Ubuntu 14.04.1 LTS
Apache/2.4.7 (Ubuntu)
PHP 5.5.9-1ubuntu4.4
External Database: PostgreSQL 9.1.14
LDAP

Regards

**Comment by arnovr** [comment]
Sorry about the massive delay, my laptop died on me and needed a new one. Which i have right now.
So it should be fixed
