### ISSUE TITLE
Graphs are showing absurd stats

### ISSUE THREAD

**Issue by Z3roCoder** [arnovr/ocusagecharts#81]
Hello. Now after getting the thing to run, I noticed that the graph shows absolutely wrong values.
According to the graph, a user of mine uses over 350 gigabyte of storage which is not possible because I limited the storage for every user to 10GB.

Any way to fix this/find out what's going wrong?

**Comment by arnovr** [comment]
Hello Z3roCoder, to bad it isn't working properly :(
I am using the owncloud core utilities to calculate the current storage for a user.
In speciifc i am using this class:
https://github.com/owncloud/core/blob/1fbf5d86df7ba4001ca826d9dfb8fad073924fde/lib/private/files/cache/homecache.php
That class uses cache from the database.

You could try clearing the cache for that user. ( Rescan file system command from command line interface )
Let me know if that works for you

**Comment by Z3roCoder** [comment]
How would this be done without loosing my data, shared folders etc under OC8? I am just finding tools and apps for OC7 or before, but not for the actual OC8, and the documentation is not helping either (Meaning, I cannot find the command for that, jus thow to put the site into maintainence mode and so on)

**Comment by arnovr** [comment]
The scanning for owncloud should NOT touch your files, it should only update the database information.

Your user's actual data files are stored on disk, and caches the information in the database.
The files are in your data directory "data/username/files/"
And indexed information in the database table "oc_filecache" ( where oc is your prefix )
Just check it out to make sure for yourself.

The command files:scan still exists in owncloud 8.0.3:
https://github.com/owncloud/core/blob/v8.0.3/apps/files/command/scan.php

On command line:
./occ files:scan USERNAME

If you want to be sure, you can just test it by making a new user upload something and rescan his information.


One side note: I do NOT know what it does with shared folders, but i am ASSUMING they are stored somewhere else outside the filecache.
You should test this behavior.

**Comment by arnovr** [comment]
By the way, if you don't want to test it on your production environment, git clone this repository, and if you are running linux or mac ( mac untested ) you could install vagrant and ansible, and do "vagrant up" on your command line.
This will put up a instance of owncloud 7 with this application for testing purposes.
