### ISSUE TITLE
fixed prefix "oc_"

### ISSUE THREAD

**Issue by tflidd** [arnovr/ocusagecharts#82]
In my owncloud (OC 7.0.5), I don't use any prefix. Unfortunately, the app searches for a table
````
SELECT * FROM `oc_uc_chartconfig` WHERE `username` ....
````
It must be hardcoded somewhere. I have a uc_chartconfig-table (I tested several chart-apps, I don't know if this app created them).

**Comment by tflidd** [comment]
Ok, I found one file: lib/entity/chartconfigrepository.php

**Comment by tflidd** [comment]
There are definitively more files...

**Comment by arnovr** [comment]
You are totally right, it is indeed hardcoded. When i created it i never thought about this issue.
The oc_uc_ prefix are the tables used by this app.

This seems like an extremely easy fix. I will fix it within the next week for sure!
