### ISSUE TITLE
App causes Redirection Loop on ownclouds index.php

### ISSUE THREAD

**Issue by stonerl** [arnovr/ocusagecharts#88]
I just installed the latest version from the appstore. Installing and using it was ok unitl I logged out. When trying to load ownclouds loginpage a got a Redirection Loop Error and could not load the page anymore.

I use ownloud v.8.1.3

**Comment by RealRancor** [comment]
@stonerl Sure you picked out the correct issue tracker? This one is for "Storage Usage / Activity Charts 3.4.5" which doesn't show this behavior for me on oC 8.1.4.

However the "Storage Charts 2 2.6.1" app is known to cause such redirects: https://github.com/hypery2k/owncloud/issues/351

**Comment by stonerl** [comment]
@RealRancor hmm I'm not sure anymore... closing this one
